// ─── Demo Mode Sample Data ────────────────────────────────────────────────────
// Shown when a user logs in with a demo PIN (1234 or 0000).
// No real Supabase data is touched.

export const DEMO_PINS = ['1234', '0000'];

export const isDemoPin = (pin: string) => DEMO_PINS.includes(pin);

export const DEMO_CANDIDATES = [
  {
    id: 'demo-c1',
    name: 'Jordan Reyes',
    email: 'jordan.reyes@example.com',
    phone: '+1 (415) 555-0182',
    role: 'Senior Full-Stack Engineer',
    company: 'Stripe',
    seniority: 'Senior',
    location: 'San Francisco, CA',
    status: 'Interviewing',
    skills: ['React', 'TypeScript', 'Node.js', 'PostgreSQL', 'AWS'],
    experience: '7 years',
    linkedinUrl: 'https://linkedin.com/in/jordanreyes-demo',
    websiteUrl: 'https://github.com/jordanreyes-demo',
    notes: 'Strong system design background. Ex-Stripe, worked on payments infra. Open to Series B+.',
    source: 'LinkedIn',
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'demo-c2',
    name: 'Priya Nair',
    email: 'priya.nair@example.com',
    phone: '+1 (212) 555-0239',
    role: 'Product Manager',
    company: 'Figma',
    seniority: 'Mid/Senior',
    location: 'New York, NY',
    status: 'New',
    skills: ['Product Strategy', 'Roadmapping', 'SQL', 'Figma', 'A/B Testing'],
    experience: '5 years',
    linkedinUrl: 'https://linkedin.com/in/priyanair-demo',
    websiteUrl: '',
    notes: 'Previously at Notion. Strong user research skills. Looking for Series A or B.',
    source: 'Referral',
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'demo-c3',
    name: 'Marcus Webb',
    email: 'marcus.webb@example.com',
    phone: '+1 (310) 555-0471',
    role: 'Lead Data Scientist',
    company: 'Netflix',
    seniority: 'Lead',
    location: 'Los Angeles, CA',
    status: 'Offer',
    skills: ['Python', 'Machine Learning', 'PyTorch', 'Spark', 'Airflow', 'SQL'],
    experience: '9 years',
    linkedinUrl: 'https://linkedin.com/in/marcuswebb-demo',
    websiteUrl: 'https://github.com/marcuswebb-demo',
    notes: 'PhD in Statistics from Stanford. Led recommendation engine team at Netflix. Passive but interested.',
    source: 'CSV Import',
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'demo-c4',
    name: 'Aisha Okonkwo',
    email: 'aisha.okonkwo@example.com',
    phone: '+1 (512) 555-0103',
    role: 'DevOps Engineer',
    company: 'HashiCorp',
    seniority: 'Senior',
    location: 'Austin, TX',
    status: 'Contacted',
    skills: ['Kubernetes', 'Terraform', 'AWS', 'CI/CD', 'Docker', 'Go'],
    experience: '6 years',
    linkedinUrl: 'https://linkedin.com/in/aishaokonkwo-demo',
    websiteUrl: '',
    notes: 'Built and managed multi-cloud infra at HashiCorp. Seeking staff-level IC role.',
    source: 'LinkedIn',
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'demo-c5',
    name: 'Tom Gallagher',
    email: 'tom.gallagher@example.com',
    phone: '+1 (617) 555-0358',
    role: 'VP of Engineering',
    company: 'HubSpot',
    seniority: 'Executive',
    location: 'Boston, MA',
    status: 'New',
    skills: ['Engineering Leadership', 'System Architecture', 'OKRs', 'Hiring', 'Java', 'Go'],
    experience: '15 years',
    linkedinUrl: 'https://linkedin.com/in/tomgallagher-demo',
    websiteUrl: '',
    notes: 'Managed 80+ eng org at HubSpot. Looking for a CTO or VP Eng role at growth-stage company.',
    source: 'Referral',
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'demo-c6',
    name: 'Sara Kim',
    email: 'sara.kim@example.com',
    phone: '+1 (206) 555-0274',
    role: 'UX Designer',
    company: 'Shopify',
    seniority: 'Mid/Senior',
    location: 'Seattle, WA',
    status: 'Interviewing',
    skills: ['Figma', 'User Research', 'Prototyping', 'Design Systems', 'Framer'],
    experience: '4 years',
    linkedinUrl: 'https://linkedin.com/in/sarakim-demo',
    websiteUrl: 'https://sarakim.design',
    notes: 'Strong portfolio with e-commerce and SaaS products. Available in 4 weeks.',
    source: 'LinkedIn',
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'demo-c7',
    name: 'Dmitri Volkov',
    email: 'dmitri.volkov@example.com',
    phone: '+1 (415) 555-0619',
    role: 'Backend Engineer',
    company: 'Cloudflare',
    seniority: 'Senior',
    location: 'Remote',
    status: 'Placed',
    skills: ['Rust', 'Go', 'Distributed Systems', 'gRPC', 'Kafka'],
    experience: '8 years',
    linkedinUrl: 'https://linkedin.com/in/dmitrivolkov-demo',
    websiteUrl: 'https://github.com/dmitrivolkov-demo',
    notes: 'Placed at TechNova Inc. Started 2 weeks ago. Great fit for infra roles.',
    source: 'LinkedIn',
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'demo-c8',
    name: 'Chloe Tran',
    email: 'chloe.tran@example.com',
    phone: '+1 (650) 555-0447',
    role: 'Growth Marketing Manager',
    company: 'Canva',
    seniority: 'Mid/Senior',
    location: 'San Jose, CA',
    status: 'Contacted',
    skills: ['SEO', 'Paid Acquisition', 'Analytics', 'HubSpot', 'Copywriting'],
    experience: '5 years',
    linkedinUrl: 'https://linkedin.com/in/chloetran-demo',
    websiteUrl: '',
    notes: 'Led growth from 0 to 2M users at Canva AU. Open to Head of Growth roles.',
    source: 'CSV Import',
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const DEMO_JOBS = [
  {
    id: 'demo-j1',
    title: 'Senior Full-Stack Engineer',
    client: 'TechNova Inc.',
    location: 'San Francisco, CA (Hybrid)',
    status: 'Sourcing',
    salaryMin: 160000,
    salaryMax: 210000,
    requirements: 'React, TypeScript, Node.js, 5+ years experience. Experience with cloud infra a plus. Strong communicator who can work cross-functionally.',
    applicants: 3,
    postedDate: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'demo-j2',
    title: 'Lead Data Scientist',
    client: 'Apex Analytics',
    location: 'New York, NY (On-site)',
    status: 'Interviewing',
    salaryMin: 190000,
    salaryMax: 240000,
    requirements: 'Python, PyTorch/TensorFlow, 8+ years experience. PhD preferred. Must have experience deploying ML models at scale.',
    applicants: 5,
    postedDate: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'demo-j3',
    title: 'VP of Engineering',
    client: 'Momentum Labs',
    location: 'Remote',
    status: 'Open',
    salaryMin: 250000,
    salaryMax: 320000,
    requirements: 'Engineering leadership 10+ years, managed 50+ eng teams, Series B or later. Strong hiring and org-building background.',
    applicants: 1,
    postedDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'demo-j4',
    title: 'Senior DevOps / Platform Engineer',
    client: 'CloudBridge Systems',
    location: 'Austin, TX (Hybrid)',
    status: 'Offer',
    salaryMin: 150000,
    salaryMax: 185000,
    requirements: 'Kubernetes, Terraform, AWS or GCP, CI/CD pipelines. 5+ years. Go experience a strong plus.',
    applicants: 4,
    postedDate: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'demo-j5',
    title: 'Head of Growth Marketing',
    client: 'Launchpad Ventures',
    location: 'Remote',
    status: 'Open',
    salaryMin: 130000,
    salaryMax: 170000,
    requirements: 'Growth marketing 5+ years, B2B SaaS preferred. Strong data analytics, SEO, paid acquisition. Experience scaling 0→1.',
    applicants: 2,
    postedDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const DEMO_CLIENTS = [
  {
    id: 'demo-cl1',
    name: 'TechNova Inc.',
    industry: 'SaaS / Developer Tools',
    location: 'San Francisco, CA',
    website: 'https://technova.example.com',
    contactName: 'Rachel Foster',
    contactEmail: 'rfoster@technova.example.com',
    contactPhone: '+1 (415) 555-0100',
    status: 'Active',
    notes: 'Series B, $40M raised. Eng team growing fast. 3 open roles with us.',
    createdAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'demo-cl2',
    name: 'Apex Analytics',
    industry: 'Data & AI',
    location: 'New York, NY',
    website: 'https://apexanalytics.example.com',
    contactName: 'James Osei',
    contactEmail: 'josei@apex.example.com',
    contactPhone: '+1 (212) 555-0200',
    status: 'Active',
    notes: 'Late-stage startup, ML-heavy team. Very selective hiring, 3+ rounds. Long lead times.',
    createdAt: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'demo-cl3',
    name: 'Momentum Labs',
    industry: 'FinTech',
    location: 'Remote',
    website: 'https://momentumlabs.example.com',
    contactName: 'Bianca Rossi',
    contactEmail: 'bianca@momentumlabs.example.com',
    contactPhone: '+1 (650) 555-0300',
    status: 'Prospect',
    notes: 'Intro call done. Looking for VP Eng urgently. Decision maker is CEO directly.',
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const DEMO_SEQUENCES = [
  {
    id: 'demo-seq1',
    name: 'Engineering Outreach - Cold',
    status: 'Active',
    enrolled: 12,
    replied: 4,
    steps: [
      { id: 's1', type: 'linkedin', delay: 0, subject: '', body: 'Hi {{name}}, saw your background at {{company}} — would love to connect about a senior eng role I\'m working on.' },
      { id: 's2', type: 'email', delay: 3, subject: 'Quick follow-up', body: 'Hi {{name}}, just wanted to follow up on my LinkedIn message. Happy to share more details if you\'re open to a quick call.' },
      { id: 's3', type: 'email', delay: 7, subject: 'Last touch', body: 'Hi {{name}}, I\'ll leave this here — if timing is ever right, I\'d love to reconnect. Best, {{recruiter}}' },
    ],
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'demo-seq2',
    name: 'Executive Search - Warm',
    status: 'Active',
    enrolled: 5,
    replied: 2,
    steps: [
      { id: 's4', type: 'email', delay: 0, subject: 'Leadership opportunity at {{company}}', body: 'Hi {{name}}, I\'m working with a fast-growing company looking for a VP Eng. Given your background leading teams at {{currentCompany}}, I thought you\'d be a great fit.' },
      { id: 's5', type: 'linkedin', delay: 5, body: 'Hi {{name}}, sent you an email last week — wanted to connect here as well in case it got buried.' },
    ],
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
  },
];
