import { Candidate, Job, Client, Placement, DashboardStats, DailyAction, AIInsight, OutreachLog } from './schemas';

// ========================================
// Mock Outreach Logs
// ========================================
export let mockOutreachLogs: OutreachLog[] = [];

// ========================================
// Mock Candidates
// ========================================
export let mockCandidates: Candidate[] = [
  {
    id: 'c_101',
    name: 'Rob Hedley',
    email: 'rob.hedley.dev@gmail.com',
    phone: '+44 7700 900123',
    location: 'Surrey, England',
    role: 'Senior React JS Front End Developer',
    company: 'SC Cleared',
    status: 'New',
    source: 'Google Search (LinkedIn)',
    rating: 5,
    skills: ['React', 'TypeScript', 'UX/UI Design', 'SC Cleared'],
    experience: '7 years',
    seniority: 'Senior',
    lastContact: '2024-03-20',
    notes: 'Incredible developer with active SC Clearance. Lives right in Surrey.',
  },
  {
    id: 'c_102',
    name: 'Igor Baluev',
    email: 'igor.baluev@outlook.co.uk',
    phone: '+44 7700 900456',
    location: 'London, England',
    role: 'Frontend UI Engineer',
    company: 'Versaterm',
    status: 'New',
    source: 'Google Search (LinkedIn)',
    rating: 4,
    skills: ['React', 'JavaScript', 'CSS/SCSS', 'UI Architecture'],
    experience: '5 years',
    seniority: 'Senior',
    lastContact: '2024-03-19',
  },
  {
    id: 'c_103',
    name: 'Reim Ryad',
    email: 'r.ryad.ml@gmail.com',
    phone: '+44 7700 900789',
    location: 'Surrey, England',
    role: 'Machine Learning & CV Engineer',
    company: 'AI Tech London',
    status: 'New',
    source: 'Google Search (LinkedIn)',
    rating: 5,
    skills: ['C++', 'Python', 'Machine Learning', 'Computer Vision'],
    experience: '8 years',
    seniority: 'Senior',
    lastContact: '2024-03-20',
    notes: 'Heavy C++ optimization background. Perfect fit for the AI role.',
  },
  {
    id: 'c_104',
    name: 'Dario Zela',
    email: 'dario.zela.ai@yahoo.co.uk',
    phone: '+44 7700 900321',
    location: 'Reading, England',
    role: 'Machine Learning Engineer',
    company: 'Data-Intensive Systems',
    status: 'New',
    source: 'Google Search (LinkedIn)',
    rating: 4,
    skills: ['C++', 'Python', 'Machine Learning', 'CUDA'],
    experience: '4 years',
    seniority: 'Mid-Level',
    lastContact: '2024-03-18',
  },
// --- BULK INJECTED REAL CANDIDATES ---
  {
    id: 'c_bulk_0_1781737310929',
    name: 'Beant Kaur',
    email: 'Requires Outreach',
    phone: 'N/A',
    location: 'UK',
    role: 'Frontend Developer | Expertise in Web and Mobile ...',
    company: 'Unknown',
    status: 'New',
    source: 'Google Search (LinkedIn)',
    rating: 3,
    skills: ['Frontend Developer | Expertise...'],
    experience: 'Unknown',
    seniority: 'Mid/Senior',
    lastContact: 'Never'
  },
  {
    id: 'c_bulk_1_1781737310929',
    name: 'Kenny Lai',
    email: 'Requires Outreach',
    phone: 'N/A',
    location: 'UK',
    role: 'Frontend Engineer',
    company: 'Unknown',
    status: 'New',
    source: 'Google Search (LinkedIn)',
    rating: 3,
    skills: ['Kenny Lai. Frontend Engineer. ...'],
    experience: 'Unknown',
    seniority: 'Mid/Senior',
    lastContact: 'Never'
  },
  {
    id: 'c_bulk_2_1781737310929',
    name: 'Sandeep Kaur Aulakh',
    email: 'Requires Outreach',
    phone: 'N/A',
    location: 'UK',
    role: 'Frontend Developer | ReactJs | Vuejs',
    company: 'Unknown',
    status: 'New',
    source: 'Google Search (LinkedIn)',
    rating: 3,
    skills: ['Sandeep Kaur Aulakh. Frontend ...'],
    experience: 'Unknown',
    seniority: 'Mid/Senior',
    lastContact: 'Never'
  },
  {
    id: 'c_bulk_3_1781737310929',
    name: 'Artur Rybak | Building High',
    email: 'Requires Outreach',
    phone: 'N/A',
    location: 'UK',
    role: 'Impact Web & Mobile Products',
    company: 'Unknown',
    status: 'New',
    source: 'Google Search (LinkedIn)',
    rating: 3,
    skills: ['Software Engineer (Frontend) |...'],
    experience: 'Unknown',
    seniority: 'Mid/Senior',
    lastContact: 'Never'
  },
  {
    id: 'c_bulk_4_1781737310929',
    name: 'Gauravjeet Singh',
    email: 'Requires Outreach',
    phone: 'N/A',
    location: 'UK',
    role: 'Senior Frontend Engineer · React / Next.js ...',
    company: 'Unknown',
    status: 'New',
    source: 'Google Search (LinkedIn)',
    rating: 3,
    skills: ['Senior Frontend Engineer · Rea...'],
    experience: 'Unknown',
    seniority: 'Mid/Senior',
    lastContact: 'Never'
  },
  {
    id: 'c_bulk_5_1781737310929',
    name: 'Vishnu Kumar',
    email: 'Requires Outreach',
    phone: 'N/A',
    location: 'UK',
    role: 'Sr. Frontend Developer | ES6+ | Typescript | React',
    company: 'Unknown',
    status: 'New',
    source: 'Google Search (LinkedIn)',
    rating: 3,
    skills: ['Vishnu Kumar. Sr. Frontend Dev...'],
    experience: 'Unknown',
    seniority: 'Mid/Senior',
    lastContact: 'Never'
  },
  {
    id: 'c_bulk_6_1781737310929',
    name: 'George Griffiths',
    email: 'Requires Outreach',
    phone: 'N/A',
    location: 'UK',
    role: 'Lead Frontend Developer at Immersive',
    company: 'Unknown',
    status: 'New',
    source: 'Google Search (LinkedIn)',
    rating: 3,
    skills: ['George Griffiths. Lead Fronten...'],
    experience: 'Unknown',
    seniority: 'Mid/Senior',
    lastContact: 'Never'
  },
  {
    id: 'c_bulk_7_1781737310929',
    name: 'David Martinez Marin',
    email: 'Requires Outreach',
    phone: 'N/A',
    location: 'UK',
    role: 'Engineering Manager & Senior FrontEnd ...',
    company: 'Unknown',
    status: 'New',
    source: 'Google Search (LinkedIn)',
    rating: 3,
    skills: ['David Martinez Marin. Engineer...'],
    experience: 'Unknown',
    seniority: 'Mid/Senior',
    lastContact: 'Never'
  },
  {
    id: 'c_bulk_8_1781737310929',
    name: 'Helen C.',
    email: 'Requires Outreach',
    phone: 'N/A',
    location: 'UK',
    role: 'Netcel',
    company: 'Unknown',
    status: 'New',
    source: 'Google Search (LinkedIn)',
    rating: 3,
    skills: ['Senior Frontend Developer (Rea...'],
    experience: 'Unknown',
    seniority: 'Mid/Senior',
    lastContact: 'Never'
  },
  {
    id: 'c_bulk_9_1781737310929',
    name: 'Varshini Sundari Babu',
    email: 'Requires Outreach',
    phone: 'N/A',
    location: 'UK',
    role: 'Frontend Developer and User Experience ...',
    company: 'Unknown',
    status: 'New',
    source: 'Google Search (LinkedIn)',
    rating: 3,
    skills: ['Varshini Sundari Babu. Fronten...'],
    experience: 'Unknown',
    seniority: 'Mid/Senior',
    lastContact: 'Never'
  },
  {
    id: 'c_bulk_10_1781737310929',
    name: 'Wenwu Wang',
    email: 'Requires Outreach',
    phone: 'N/A',
    location: 'UK',
    role: 'Professor of Signal Processing and Machine ...',
    company: 'Unknown',
    status: 'New',
    source: 'Google Search (LinkedIn)',
    rating: 3,
    skills: ['Professor of Signal Processing...'],
    experience: 'Unknown',
    seniority: 'Mid/Senior',
    lastContact: 'Never'
  },
  {
    id: 'c_bulk_11_1781737310929',
    name: 'Marco Volino',
    email: 'Requires Outreach',
    phone: 'N/A',
    location: 'UK',
    role: 'Senior Lecturer @ University of Surrey',
    company: 'Unknown',
    status: 'New',
    source: 'Google Search (LinkedIn)',
    rating: 3,
    skills: ['Senior Lecturer @ University o...'],
    experience: 'Unknown',
    seniority: 'Mid/Senior',
    lastContact: 'Never'
  },
  {
    id: 'c_bulk_12_1781737310929',
    name: 'Yi',
    email: 'Requires Outreach',
    phone: 'N/A',
    location: 'UK',
    role: 'Zhe Song',
    company: 'Unknown',
    status: 'New',
    source: 'Google Search (LinkedIn)',
    rating: 3,
    skills: ['I am a Professor of Computer V...'],
    experience: 'Unknown',
    seniority: 'Mid/Senior',
    lastContact: 'Never'
  },
  {
    id: 'c_bulk_13_1781737310929',
    name: 'Lucy Jackson',
    email: 'Requires Outreach',
    phone: 'N/A',
    location: 'UK',
    role: 'Data Scientist @ Physics X | PhD in Machine Learning',
    company: 'Unknown',
    status: 'New',
    source: 'Google Search (LinkedIn)',
    rating: 3,
    skills: ['Data Scientist @ Physics X | P...'],
    experience: 'Unknown',
    seniority: 'Mid/Senior',
    lastContact: 'Never'
  },
  {
    id: 'c_bulk_14_1781737310929',
    name: 'Will Binning',
    email: 'Requires Outreach',
    phone: 'N/A',
    location: 'UK',
    role: 'Logic and Reasoning in Board Game Understanding',
    company: 'Unknown',
    status: 'New',
    source: 'Google Search (LinkedIn)',
    rating: 3,
    skills: ['PHD Researcher in Machine Lear...'],
    experience: 'Unknown',
    seniority: 'Mid/Senior',
    lastContact: 'Never'
  },
  {
    id: 'c_bulk_15_1781737310929',
    name: 'Youssef Abdelrahim',
    email: 'Requires Outreach',
    phone: 'N/A',
    location: 'UK',
    role: 'MSc in Computer Vision, Robotics ...',
    company: 'Unknown',
    status: 'New',
    source: 'Google Search (LinkedIn)',
    rating: 3,
    skills: ['MSc in Computer Vision, Roboti...'],
    experience: 'Unknown',
    seniority: 'Mid/Senior',
    lastContact: 'Never'
  },
  {
    id: 'c_bulk_16_1781737310929',
    name: 'Ben Sanders',
    email: 'Requires Outreach',
    phone: 'N/A',
    location: 'UK',
    role: 'Machine Learning Specialist at Cloud Imperium Games',
    company: 'Unknown',
    status: 'New',
    source: 'Google Search (LinkedIn)',
    rating: 3,
    skills: ['Education. University of Surre...'],
    experience: 'Unknown',
    seniority: 'Mid/Senior',
    lastContact: 'Never'
  },
  {
    id: 'c_bulk_17_1781737310929',
    name: 'Harikrishnan K S',
    email: 'Requires Outreach',
    phone: 'N/A',
    location: 'UK',
    role: 'Senior Machine Learning Engineer | Data Scientist',
    company: 'Unknown',
    status: 'New',
    source: 'Google Search (LinkedIn)',
    rating: 3,
    skills: ['Harikrishnan K S. Senior Machi...'],
    experience: 'Unknown',
    seniority: 'Mid/Senior',
    lastContact: 'Never'
  },
  {
    id: 'c_bulk_18_1781737310929',
    name: 'Behram Khanzada',
    email: 'Requires Outreach',
    phone: 'N/A',
    location: 'UK',
    role: 'University of Surrey MSc AI Student',
    company: 'Unknown',
    status: 'New',
    source: 'Google Search (LinkedIn)',
    rating: 3,
    skills: ['University of Surrey MSc AI St...'],
    experience: 'Unknown',
    seniority: 'Mid/Senior',
    lastContact: 'Never'
  },
  {
    id: 'c_bulk_19_1781737310929',
    name: 'Nawafa Hassainar | Computer Vision, Machine Learning & Robotics',
    email: 'Requires Outreach',
    phone: 'N/A',
    location: 'UK',
    role: '',
    company: 'Unknown',
    status: 'New',
    source: 'Google Search (LinkedIn)',
    rating: 3,
    skills: ['Education ; University of Surr...'],
    experience: 'Unknown',
    seniority: 'Mid/Senior',
    lastContact: 'Never'
  },
  {
    id: 'c_bulk_20_1781737310929',
    name: 'Johnny Hall',
    email: 'Requires Outreach',
    phone: 'N/A',
    location: 'UK',
    role: 'Full',
    company: 'Unknown',
    status: 'New',
    source: 'Google Search (LinkedIn)',
    rating: 3,
    skills: ['Full-Stack Engineer | React, T...'],
    experience: 'Unknown',
    seniority: 'Mid/Senior',
    lastContact: 'Never'
  },
  {
    id: 'c_bulk_21_1781737310929',
    name: 'Ian London',
    email: 'Requires Outreach',
    phone: 'N/A',
    location: 'UK',
    role: 'Senior Software Engineer, TypeScript React/Redux + ...',
    company: 'Unknown',
    status: 'New',
    source: 'Google Search (LinkedIn)',
    rating: 3,
    skills: ['Ian London. Senior Software En...'],
    experience: 'Unknown',
    seniority: 'Mid/Senior',
    lastContact: 'Never'
  },
  {
    id: 'c_bulk_22_1781737310929',
    name: 'Antonio Redondo',
    email: 'Requires Outreach',
    phone: 'N/A',
    location: 'UK',
    role: 'Front',
    company: 'Unknown',
    status: 'New',
    source: 'Google Search (LinkedIn)',
    rating: 3,
    skills: ['Front-end and React Native dev...'],
    experience: 'Unknown',
    seniority: 'Mid/Senior',
    lastContact: 'Never'
  },
  {
    id: 'c_bulk_23_1781737310929',
    name: 'Kateryna Havrenko',
    email: 'Requires Outreach',
    phone: 'N/A',
    location: 'UK',
    role: 'Frontend Developer | React, Typescript | FinTech',
    company: 'Unknown',
    status: 'New',
    source: 'Google Search (LinkedIn)',
    rating: 3,
    skills: ['Frontend Developer | React, Ty...'],
    experience: 'Unknown',
    seniority: 'Mid/Senior',
    lastContact: 'Never'
  },
  {
    id: 'c_bulk_24_1781737310929',
    name: 'Tom A.',
    email: 'Requires Outreach',
    phone: 'N/A',
    location: 'UK',
    role: 'React Developer',
    company: 'Unknown',
    status: 'New',
    source: 'Google Search (LinkedIn)',
    rating: 3,
    skills: ['Tom A. React Developer. Xanda ...'],
    experience: 'Unknown',
    seniority: 'Mid/Senior',
    lastContact: 'Never'
  },
  {
    id: 'c_bulk_25_1781737310929',
    name: 'Geoff Ford',
    email: 'Requires Outreach',
    phone: 'N/A',
    location: 'UK',
    role: 'Senior JavaScript Developer (Front End/Back ...',
    company: 'Unknown',
    status: 'New',
    source: 'Google Search (LinkedIn)',
    rating: 3,
    skills: ['Geoff Ford. Senior JavaScript ...'],
    experience: 'Unknown',
    seniority: 'Mid/Senior',
    lastContact: 'Never'
  },
  {
    id: 'c_bulk_26_1781737310929',
    name: 'Archie Martin',
    email: 'Requires Outreach',
    phone: 'N/A',
    location: 'UK',
    role: 'Fullstack Engineer | Ruby on Rails, React ...',
    company: 'Unknown',
    status: 'New',
    source: 'Google Search (LinkedIn)',
    rating: 3,
    skills: ['Fullstack Engineer | Ruby on R...'],
    experience: 'Unknown',
    seniority: 'Mid/Senior',
    lastContact: 'Never'
  },
  {
    id: 'c_bulk_27_1781737310929',
    name: 'Emma Sargeant',
    email: 'Requires Outreach',
    phone: 'N/A',
    location: 'UK',
    role: 'Frontend Engineer | React | React Native',
    company: 'Unknown',
    status: 'New',
    source: 'Google Search (LinkedIn)',
    rating: 3,
    skills: ['Frontend Engineer | React | Re...'],
    experience: 'Unknown',
    seniority: 'Mid/Senior',
    lastContact: 'Never'
  },
  {
    id: 'c_bulk_28_1781737310929',
    name: 'James Little',
    email: 'Requires Outreach',
    phone: 'N/A',
    location: 'UK',
    role: 'React Frontend Developer',
    company: 'Unknown',
    status: 'New',
    source: 'Google Search (LinkedIn)',
    rating: 3,
    skills: ['James Little. React Frontend D...'],
    experience: 'Unknown',
    seniority: 'Mid/Senior',
    lastContact: 'Never'
  },
  {
    id: 'c_bulk_29_1781737310929',
    name: 'Goeun Lee',
    email: 'Requires Outreach',
    phone: 'N/A',
    location: 'UK',
    role: 'Frontend Engineer at Cloudflare | Specializing in React ...',
    company: 'Unknown',
    status: 'New',
    source: 'Google Search (LinkedIn)',
    rating: 3,
    skills: ['Frontend Engineer at Cloudflar...'],
    experience: 'Unknown',
    seniority: 'Mid/Senior',
    lastContact: 'Never'
  },
  {
    id: 'c_bulk_30_1781737310929',
    name: 'Sam Shannon',
    email: 'Requires Outreach',
    phone: 'N/A',
    location: 'UK',
    role: 'Senior Software Engineer at Tripadvisor',
    company: 'Unknown',
    status: 'New',
    source: 'Google Search (LinkedIn)',
    rating: 3,
    skills: ['Senior Software Engineer at Tr...'],
    experience: 'Unknown',
    seniority: 'Mid/Senior',
    lastContact: 'Never'
  },
  {
    id: 'c_bulk_31_1781737310929',
    name: 'Hassan Hunjra',
    email: 'Requires Outreach',
    phone: 'N/A',
    location: 'UK',
    role: 'CS Student @ University of Surrey',
    company: 'Unknown',
    status: 'New',
    source: 'Google Search (LinkedIn)',
    rating: 3,
    skills: ['CS Student @ University of Sur...'],
    experience: 'Unknown',
    seniority: 'Mid/Senior',
    lastContact: 'Never'
  },
  {
    id: 'c_bulk_32_1781737310929',
    name: 'John Robinson',
    email: 'Requires Outreach',
    phone: 'N/A',
    location: 'UK',
    role: 'Senior Cloud Engineer, with Medidata Solutions, a ...',
    company: 'Unknown',
    status: 'New',
    source: 'Google Search (LinkedIn)',
    rating: 3,
    skills: ['John Robinson. Senior Cloud En...'],
    experience: 'Unknown',
    seniority: 'Mid/Senior',
    lastContact: 'Never'
  },
  {
    id: 'c_bulk_33_1781737310929',
    name: 'Phil Davies',
    email: 'Requires Outreach',
    phone: 'N/A',
    location: 'UK',
    role: 'Software Engineer',
    company: 'Unknown',
    status: 'New',
    source: 'Google Search (LinkedIn)',
    rating: 3,
    skills: ['Software Engineer · Possesses ...'],
    experience: 'Unknown',
    seniority: 'Mid/Senior',
    lastContact: 'Never'
  },
  {
    id: 'c_bulk_34_1781737310929',
    name: 'James O\'Farrell MSc BEng',
    email: 'Requires Outreach',
    phone: 'N/A',
    location: 'UK',
    role: 'Software Engineer',
    company: 'Unknown',
    status: 'New',
    source: 'Google Search (LinkedIn)',
    rating: 3,
    skills: ['James O\'Farrell MSc BEng. Soft...'],
    experience: 'Unknown',
    seniority: 'Mid/Senior',
    lastContact: 'Never'
  },
  {
    id: 'c_bulk_35_1781737310930',
    name: 'Tom Finlayson',
    email: 'Requires Outreach',
    phone: 'N/A',
    location: 'UK',
    role: 'Senior Software Engineer',
    company: 'Unknown',
    status: 'New',
    source: 'Google Search (LinkedIn)',
    rating: 3,
    skills: ['Senior Software Engineer · Exp...'],
    experience: 'Unknown',
    seniority: 'Mid/Senior',
    lastContact: 'Never'
  },
  {
    id: 'c_bulk_36_1781737310930',
    name: 'Emilia L.',
    email: 'Requires Outreach',
    phone: 'N/A',
    location: 'UK',
    role: 'Software Engineer at Abnormal Security',
    company: 'Unknown',
    status: 'New',
    source: 'Google Search (LinkedIn)',
    rating: 3,
    skills: ['Software Engineer at Abnormal ...'],
    experience: 'Unknown',
    seniority: 'Mid/Senior',
    lastContact: 'Never'
  },
  {
    id: 'c_bulk_37_1781737310930',
    name: 'Matthew G.',
    email: 'Requires Outreach',
    phone: 'N/A',
    location: 'UK',
    role: 'Senior Software Engineer',
    company: 'Unknown',
    status: 'New',
    source: 'Google Search (LinkedIn)',
    rating: 3,
    skills: ['Matthew G. Senior Software Eng...'],
    experience: 'Unknown',
    seniority: 'Mid/Senior',
    lastContact: 'Never'
  },
  {
    id: 'c_bulk_38_1781737310930',
    name: 'Aviraj Singh',
    email: 'Requires Outreach',
    phone: 'N/A',
    location: 'UK',
    role: 'Software / Product Engineer',
    company: 'Unknown',
    status: 'New',
    source: 'Google Search (LinkedIn)',
    rating: 3,
    skills: ['... Software Engineer at Layer...'],
    experience: 'Unknown',
    seniority: 'Mid/Senior',
    lastContact: 'Never'
  },
  {
    id: 'c_bulk_39_1781737310930',
    name: 'Louis Field',
    email: 'Requires Outreach',
    phone: 'N/A',
    location: 'UK',
    role: 'Software Engineer',
    company: 'Unknown',
    status: 'New',
    source: 'Google Search (LinkedIn)',
    rating: 3,
    skills: ['Software Engineer · Software E...'],
    experience: 'Unknown',
    seniority: 'Mid/Senior',
    lastContact: 'Never'
  },
  {
    id: 'c_bulk_40_1781737310930',
    name: 'Dimitry London',
    email: 'Requires Outreach',
    phone: 'N/A',
    location: 'UK',
    role: 'Software Engineer, Market Data, High ...',
    company: 'Unknown',
    status: 'New',
    source: 'Google Search (LinkedIn)',
    rating: 3,
    skills: ['... London\'s profile on Linked...'],
    experience: 'Unknown',
    seniority: 'Mid/Senior',
    lastContact: 'Never'
  },
  {
    id: 'c_bulk_41_1781737310930',
    name: 'Joshua Wong',
    email: 'Requires Outreach',
    phone: 'N/A',
    location: 'UK',
    role: 'Software Engineer | C++, Python & Swift',
    company: 'Unknown',
    status: 'New',
    source: 'Google Search (LinkedIn)',
    rating: 3,
    skills: ['... London · 288 connections o...'],
    experience: 'Unknown',
    seniority: 'Mid/Senior',
    lastContact: 'Never'
  },
  {
    id: 'c_bulk_42_1781737310930',
    name: 'Andrew Turner',
    email: 'Requires Outreach',
    phone: 'N/A',
    location: 'UK',
    role: 'Software Engineer | Open to London based roles',
    company: 'Unknown',
    status: 'New',
    source: 'Google Search (LinkedIn)',
    rating: 3,
    skills: ['Software Engineer | TypeScript...'],
    experience: 'Unknown',
    seniority: 'Mid/Senior',
    lastContact: 'Never'
  },
  {
    id: 'c_bulk_43_1781737310930',
    name: 'Dominic London',
    email: 'Requires Outreach',
    phone: 'N/A',
    location: 'UK',
    role: 'Software Engineer (Java, C++, Unreal, Unity',
    company: 'Unknown',
    status: 'New',
    source: 'Google Search (LinkedIn)',
    rating: 3,
    skills: ['Dominic London. Software Engin...'],
    experience: 'Unknown',
    seniority: 'Mid/Senior',
    lastContact: 'Never'
  },
  {
    id: 'c_bulk_44_1781737310930',
    name: 'Terry Clark',
    email: 'Requires Outreach',
    phone: 'N/A',
    location: 'UK',
    role: 'Mid Level C++, DirectX12, React JS',
    company: 'Unknown',
    status: 'New',
    source: 'Google Search (LinkedIn)',
    rating: 3,
    skills: ['Terry Clark. Mid Level C++, Di...'],
    experience: 'Unknown',
    seniority: 'Mid/Senior',
    lastContact: 'Never'
  },
  {
    id: 'c_bulk_45_1781737310930',
    name: 'David Z.',
    email: 'Requires Outreach',
    phone: 'N/A',
    location: 'UK',
    role: 'Software Engineer | Full',
    company: 'Unknown',
    status: 'New',
    source: 'Google Search (LinkedIn)',
    rating: 3,
    skills: ['... London, specializing in C/...'],
    experience: 'Unknown',
    seniority: 'Mid/Senior',
    lastContact: 'Never'
  },
  {
    id: 'c_bulk_46_1781737310930',
    name: 'George Marklow',
    email: 'Requires Outreach',
    phone: 'N/A',
    location: 'UK',
    role: 'Software Engineer at Bank of America',
    company: 'Unknown',
    status: 'New',
    source: 'Google Search (LinkedIn)',
    rating: 3,
    skills: ['* DevOps: Git, Azure DevOps. M...'],
    experience: 'Unknown',
    seniority: 'Mid/Senior',
    lastContact: 'Never'
  },
  {
    id: 'c_bulk_47_1781737310930',
    name: 'Ronnie Sharif',
    email: 'Requires Outreach',
    phone: 'N/A',
    location: 'UK',
    role: 'Engineering Manager at NVIDIA',
    company: 'Unknown',
    status: 'New',
    source: 'Google Search (LinkedIn)',
    rating: 3,
    skills: ['... London · Location: San Jos...'],
    experience: 'Unknown',
    seniority: 'Mid/Senior',
    lastContact: 'Never'
  },
  {
    id: 'c_bulk_48_1781737310930',
    name: 'Geoffrey Daniels',
    email: 'Requires Outreach',
    phone: 'N/A',
    location: 'UK',
    role: 'Engineering Leader | C++, Python, SLAM',
    company: 'Unknown',
    status: 'New',
    source: 'Google Search (LinkedIn)',
    rating: 3,
    skills: ['Engineering Leader | Principal...'],
    experience: 'Unknown',
    seniority: 'Mid/Senior',
    lastContact: 'Never'
  },
  {
    id: 'c_bulk_49_1781737310930',
    name: 'Jonathan Mercier',
    email: 'Requires Outreach',
    phone: 'N/A',
    location: 'UK',
    role: 'Ganady',
    company: 'Unknown',
    status: 'New',
    source: 'Google Search (LinkedIn)',
    rating: 3,
    skills: ['Senior Software Engineer | Rus...'],
    experience: 'Unknown',
    seniority: 'Mid/Senior',
    lastContact: 'Never'
  }
];

// ========================================
// Mock Jobs
// ========================================
export let mockJobs: Job[] = [
  {
    id: 'j_01',
    title: 'Senior Frontend Developer (React + UX/UI)',
    client: 'Safe Software',
    clientId: 'cl_01',
    location: 'Surrey, England (Hybrid)',
    type: 'Full-time',
    salary: '£80k - £110k',
    status: 'Open',
    priority: 'High',
    postedDate: '2024-03-15',
    applicants: 2,
    requirements: ['React', 'UX/UI Design', 'TypeScript', 'Wireframing', '5+ years experience'],
  },
  {
    id: 'j_02',
    title: 'AI/ML Software Engineer (C++)',
    client: 'Creativity Software (SS8)',
    clientId: 'cl_02',
    location: 'Surrey, England (On-site)',
    type: 'Full-time',
    salary: '£90k - £130k',
    status: 'Open',
    priority: 'Medium',
    postedDate: '2024-03-10',
    applicants: 2,
    requirements: ['C++', 'Machine Learning', 'Deep Learning', 'Algorithm Optimization'],
  }
];

// ========================================
// Mock Clients
// ========================================
export let mockClients: Client[] = [
  {
    id: 'cl_01',
    companyName: 'Safe Software',
    industry: 'Enterprise Software',
    location: 'Surrey, England',
    status: 'Active',
    contactPerson: 'David Wright',
    email: 'david.wright@safesoftware.co.uk',
    openRoles: 1,
    totalPlacements: 0,
    activeSince: '2024-01-15',
    notes: 'Actively hiring frontend talent to revamp their core product UI.',
  },
  {
    id: 'cl_02',
    companyName: 'Creativity Software (SS8)',
    industry: 'Telecommunications Software',
    location: 'Surrey, England',
    status: 'Active',
    contactPerson: 'Sarah Kensington',
    email: 'sarah@creativitysoftware.co.uk',
    openRoles: 1,
    totalPlacements: 0,
    activeSince: '2024-02-01',
    notes: 'Expanding their Surrey office. Focus on high-performance C++ ML engineers.',
  },
  {
    id: 'cl_03',
    companyName: 'Electronic Arts (EA)',
    industry: 'Video Games',
    location: 'Guildford, Surrey',
    status: 'Prospect',
    contactPerson: 'James McMillan',
    email: 'jmcmillan@ea.com',
    openRoles: 0,
    totalPlacements: 0,
    activeSince: '',
    notes: 'Massive presence in Guildford. Great potential target for C++ and UI engineers.',
  },
  {
    id: 'cl_04',
    companyName: 'McLaren Applied',
    industry: 'Automotive / Tech',
    location: 'Woking, Surrey',
    status: 'Prospect',
    contactPerson: 'Chloe Davies',
    email: 'chloe.davies@mclaren.com',
    openRoles: 0,
    totalPlacements: 0,
    activeSince: '',
    notes: 'High-tech engineering firm. Always looking for embedded and ML talent.',
  },
  {
    id: 'cl_05',
    companyName: 'BAE Systems',
    industry: 'Defense & Aerospace',
    location: 'Frimley, Surrey',
    status: 'Prospect',
    contactPerson: "Liam O'Connor",
    email: 'liam.oconnor@baesystems.com',
    openRoles: 0,
    totalPlacements: 0,
    activeSince: '',
    notes: 'Huge contractor in Surrey. Needs SC-cleared developers and data scientists.',
  }
];

// ========================================
// Mock Placements
// ========================================
export let mockPlacements: Placement[] = [];

// ========================================
// Mock Dashboard Stats
// ========================================
export const mockDashboardStats: DashboardStats = {
  activeCandidates: 0,
  activeJobs: 2,
  activeClients: 1,
  placementsThisMonth: 0,
  revenueThisMonth: 0,
  stalledOpportunities: 0,
};

// ========================================
// Mock Daily Actions
// ========================================
export let mockDailyActions: DailyAction[] = [];

// ========================================
// Mock AI Insights
// ========================================
export let mockAIInsights: AIInsight[] = [];

// ========================================
// Pipeline stage definitions
// ========================================
export const candidatePipelineStages = [
  'New',
  'Contacted',
  'Engaged',
  'Interview',
  'Submitted',
  'Placed',
  'Rejected',
] as const;

export const jobPipelineStages = [
  'Open',
  'Sourcing',
  'Interviewing',
  'Offer',
  'Filled',
] as const;

// ========================================
// Status color mapping
// ========================================
export const statusColors: Record<string, string> = {
  // Candidate statuses
  'New': 'badge-blue',
  'Contacted': 'badge-neutral',
  'Engaged': 'badge-blue',
  'Interview': 'badge-amber',
  'Submitted': 'badge-amber',
  'Placed': 'badge-green',
  'Rejected': 'badge-red',
  // Job statuses
  'Open': 'badge-blue',
  'Sourcing': 'badge-amber',
  'Interviewing': 'badge-amber',
  'Offer': 'badge-green',
  'Filled': 'badge-green',
  // Client statuses
  'Active': 'badge-green',
  'Inactive': 'badge-neutral',
  'Prospect': 'badge-blue',
};

// ========================================
// Mock External Leads (Simulating Apollo.io / LinkedIn)
// ========================================
export const mockExternalLeads = [
  {
    id: 'ext_1',
    name: 'Eleanor Vance',
    email: 'eleanor.v@example.com',
    linkedinUrl: 'https://linkedin.com/in/eleanorv',
    skills: ['React', 'Next.js', 'TypeScript', 'Tailwind'],
    seniority: 'Senior',
    source: 'LinkedIn Sourcing',
    notes: 'Strong frontend background, previously at Vercel.',
  },
  {
    id: 'ext_2',
    name: 'Marcus Thorne',
    email: 'm.thorne@example.com',
    linkedinUrl: 'https://linkedin.com/in/mthorne',
    skills: ['Python', 'Django', 'AWS', 'PostgreSQL'],
    seniority: 'Lead',
    source: 'Apollo.io',
    notes: 'Lead backend engineer at a fintech startup.',
  },
  {
    id: 'ext_3',
    name: 'Sophia Reynolds',
    email: 'sophia.r@example.com',
    linkedinUrl: 'https://linkedin.com/in/sophia-reynolds',
    skills: ['Figma', 'UI/UX', 'Design Systems', 'User Research'],
    seniority: 'Senior',
    source: 'Dribbble Scraping',
    notes: 'Incredible portfolio, heavily focused on SaaS dashboards.',
  },
  {
    id: 'ext_4',
    name: 'Julian Bates',
    email: 'jbates99@example.com',
    linkedinUrl: 'https://linkedin.com/in/julian-bates',
    skills: ['Go', 'Kubernetes', 'Terraform', 'GCP'],
    seniority: 'Staff',
    source: 'GitHub',
    notes: 'Active open-source contributor to container orchestration tools.',
  },
  {
    id: 'ext_5',
    name: 'Aria Chen',
    email: 'aria.chen.dev@example.com',
    linkedinUrl: 'https://linkedin.com/in/ariachen',
    skills: ['React Native', 'Swift', 'Kotlin', 'Mobile Arch'],
    seniority: 'Senior',
    source: 'LinkedIn Sourcing',
    notes: 'Built 3 top-100 apps in the App Store.',
  }
];
