// Generated by eve. Do not edit by hand.

import * as module_0 from "../../agent.ts";
import * as module_1 from "../../channels/eve.ts";
import * as module_2 from "../../tools/get_clients.ts";

export const moduleMap = Object.freeze({
  "nodes": Object.freeze({
      "__root__": Object.freeze({
              "modules": Object.freeze({
                  "agent.ts": module_0,
                  "channels/eve.ts": module_1,
                  "tools/get_clients.ts": module_2
                })
            })
    })
});

export default moduleMap;
