// Generated by eve. Do not edit by hand.
import { POST } from "./workflows.mjs";
import { getWorld as __eveGetWorkflowWorld } from "file:///C:/Users/senti/OneDrive/Desktop/MVP/recruitment-command-center/node_modules/eve/dist/src/internal/workflow/runtime.js";

try {
  const __eveWorkflowWorld = await __eveGetWorkflowWorld();
  if (typeof __eveWorkflowWorld?.registerHandler === "function") {
    __eveWorkflowWorld.registerHandler("__eve_wkf_workflow_", POST);
  }
} catch (err) {
  console.warn("[eve] Failed to register direct workflow queue handlers:", err);
}

export default async ({ req }) => {
  return await POST(req);
};
