// Generated by eve. Do not edit by hand.
import type { InferChannelMetadata } from "eve/channels";

declare module "eve/channels" {
  interface ChannelMetadataMap {}
  interface ChannelReferenceMap {}
}
