// Generated by eve. Do not edit by hand.
import { POST } from "../../../../../../node_modules/eve/.eve/workflow-cache/cb3cc7a82a04/workflows.mjs";

export default async ({ req }) => {
  return await POST(req);
};
