// Generated by eve. Do not edit by hand.

export const moduleMap = Object.freeze({
  "nodes": Object.freeze({
      "__root__": Object.freeze({
              "modules": Object.freeze({})
            })
    })
});

export default moduleMap;
